export const styles = {
  weights: {
    light: 'font-light',
    regular: 'font-regular',
    medium: 'font-medium',
    semibold: 'font-semibold',
    bold: 'font-bold',
    extrabold: 'font-extrabold',
    black: 'font-black',
  },
  fontSizes: {
    'text-2xs': 'text-2xs',
    'text-xs': 'text-xs',
    'text-sm': 'text-sm',
    'text-md': 'text-md',
    'text-lg': 'text-lg',
    'text-xl': 'text-xl',
    'display-xs': 'text-display-xs',
    'display-sm': 'text-display-sm',
    'display-md': 'text-display-md',
    'display-lg': 'text-display-lg',
    'display-xl': 'text-display-xl',
    'display-2xl': 'text-display-2xl',
  },
  align: {
    center: 'text-center',
    left: 'text-left',
    right: 'text-right',
    justify: 'text-justify',
  },
  transform: {
    none: 'normal-case',
    lowercase: 'lowercase',
    uppercase: 'uppercase',
    capitalize: 'capitalize',
  },
  gutter: 'mb-4',
  noWrap: 'whitespace-nowrap overflow-hidden text-ellipsis',
}
