export { default as CourseCardSkeleton } from './CourseCard'
export { default as CourseListItemCardSkeleton } from './CourseListItemCard'
export { default as QuestionFormSkeleton } from './QuestionForm'
export { default as GeneralFormSkeleton } from './GeneralForm'
export { default as Skeleton } from './Skeleton'
